%YAML 1.3
---
- Key: [Snipping Tool, pressed]
- KeyPress:
  - Print
  - click
...
---
- Key: [Emoji Smiley Heart Eyes, pressed]
- KeyPress:
  - [Control_L, Shift_L, u]
  - click
- KeyPress:
  - '1'
  - click
- KeyPress:
  - f
  - click
- KeyPress:
  - '6'
  - click
- KeyPress:
  - '0'
  - click
- KeyPress:
  - d
  - click
- KeyPress:
  - KP_Enter
  - click
...
---
- Key: [Emoji Crying Face, pressed]
- KeyPress:
  - [Control_L, Shift_L, u]
  - click
- KeyPress:
  - '1'
  - click
- KeyPress:
  - f
  - click
- KeyPress:
  - '6'
  - click
- KeyPress:
  - '2'
  - click
- KeyPress:
  - d
  - click
- KeyPress:
  - KP_Enter
  - click
...
---
- Key: [Emoji Smiley, pressed]
- KeyPress:
  - [Control_L, Shift_L, u]
  - click
- KeyPress:
  - '1'
  - click
- KeyPress:
  - f
  - click
- KeyPress:
  - '6'
  - click
- KeyPress:
  - '0'
  - click
- KeyPress:
  - '0'
  - click
- KeyPress:
  - KP_Enter
  - click
...
---
- Key: [Emoji Smilie With Tears, pressed]
- KeyPress:
  - [Control_L, Shift_L, u]
  - click
- KeyPress:
  - '1'
  - click
- KeyPress:
  - f
  - click
- KeyPress:
  - '6'
  - click
- KeyPress:
  - '0'
  - click
- KeyPress:
  - '2'
  - click
- KeyPress:
  - KP_Enter
  - click
...
---
- Key: [Open Emoji Panel, pressed]
- KeyPress:
  - [Control_L, Shift_L, u]
  - click
- KeyPress:
  - '1'
  - click
- KeyPress:
  - f
  - click
- KeyPress:
  - '4'
  - click
- KeyPress:
  - '4'
  - click
- KeyPress:
  - d
  - click
- KeyPress:
  - KP_Enter
  - click
...
